# Generated by Django 4.1.1 on 2022-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/%Y/%m/%d/"),
        ),
    ]
